// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmVwgV9gIGnkeg3h2xTjJ4ot80i4vZ98w',
    appId: '1:221801700856:web:99d904cd75a3a7a82d0a0d',
    messagingSenderId: '221801700856',
    projectId: 'store-app-b20e4',
    authDomain: 'store-app-b20e4.firebaseapp.com',
    storageBucket: 'store-app-b20e4.appspot.com',
    measurementId: 'G-K6FT5E6BZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT3TncMtLD92m9IHO7WeDRpJXDugaUVOc',
    appId: '1:221801700856:android:b7d26c4472ecfb7f2d0a0d',
    messagingSenderId: '221801700856',
    projectId: 'store-app-b20e4',
    storageBucket: 'store-app-b20e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUGucaUvGH88SIXPmcQsMpyJmHJoHnwr4',
    appId: '1:221801700856:ios:62414f1646e2d14d2d0a0d',
    messagingSenderId: '221801700856',
    projectId: 'store-app-b20e4',
    storageBucket: 'store-app-b20e4.appspot.com',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUGucaUvGH88SIXPmcQsMpyJmHJoHnwr4',
    appId: '1:221801700856:ios:62414f1646e2d14d2d0a0d',
    messagingSenderId: '221801700856',
    projectId: 'store-app-b20e4',
    storageBucket: 'store-app-b20e4.appspot.com',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmVwgV9gIGnkeg3h2xTjJ4ot80i4vZ98w',
    appId: '1:221801700856:web:672e56a2020060d32d0a0d',
    messagingSenderId: '221801700856',
    projectId: 'store-app-b20e4',
    authDomain: 'store-app-b20e4.firebaseapp.com',
    storageBucket: 'store-app-b20e4.appspot.com',
    measurementId: 'G-PLJC4E05DS',
  );
}
